language: ruby
rvm:
  - 2.3.3

install:
  - bundle install
script: 
  - bundle exec jekyll build 
  - rake check

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
